grails-app/domain/testtask/PriceList.groovy
package testtask

class PriceList{

    Integer codeOfProduct
    Date beginDate
    Date endDate
    Integer price

    static constraints = {
    }
}

grails-app/controllers/testtask/PriceListController.groovy
package testtask


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class PriceListController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond PriceList.list(params), model: [priceListInstanceCount: PriceList.count()]
    }

    def show(PriceList priceListInstance) {
        respond priceListInstance
    }

    def create = {
        respond new PriceList(params)
    }
    /*
    *
    * изменение дат
    *
    * */

    def changeDates(PriceList priceList) {
        if (PriceList.findByCodeOfProduct(priceList.codeOfProduct)) {

            def price = PriceList.findAllByCodeOfProduct(priceList.codeOfProduct).toSorted(new PriceListCompare())

            for (it in price) {
                if (it.beginDate >= priceList.beginDate && it.endDate <= priceList.endDate) {
                    PriceList deletedItem = PriceList.findById(it.id)
                    deletedItem.delete();
                    continue
                }

                if (it.beginDate <= priceList.beginDate && it.endDate >= priceList.endDate) {
                    PriceList item = PriceList.findById(it.id)
                    new PriceList(codeOfProduct: item.codeOfProduct, beginDate: priceList.endDate.plus(1), endDate: item.endDate, price: item.price).save(flush: true, failOnError: true)
                    item.endDate = priceList.beginDate.minus(1)
                    item.save()
                    break
                }

                if (it.beginDate >= priceList.beginDate && it.endDate >= priceList.endDate && it.beginDate <= priceList.endDate) {
                    PriceList item = PriceList.findById(it.id)
                    item.beginDate = priceList.endDate.plus(1)
                    item.save()
                }

                if (it.beginDate <= priceList.beginDate && it.endDate <= priceList.endDate && it.endDate >= priceList.beginDate) {
                    PriceList item = PriceList.findById(it.id)
                    item.endDate = priceList.beginDate.minus(1)
                    item.save(flush: true, failOnError: true)
                }
            }
            priceList.save flush: true
            redirect action: 'index'

        } else {
            priceList.save flush: true
            redirect priceList
        }
    }

    def edit(PriceList priceListInstance) {
        respond priceListInstance
    }

    @Transactional
    def delete(PriceList priceListInstance) {

        if (priceListInstance == null) {
            notFound()
            return
        }

        priceListInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'PriceList.label', default: 'PriceList'), priceListInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'priceList.label', default: 'PriceList'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
		<g:layoutHead/>
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><asset:image src="grails_logo.png" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
	</body>
</html>

grails-app/views/priceList/_form.gsp
<%@ page import="testtask.PriceList" %>



<div class="fieldcontain ${hasErrors(bean: priceListInstance, field: 'beginDate', 'error')} required">
	<label for="beginDate">
		<g:message code="priceList.beginDate.label" default="Begin Date" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="beginDate" precision="day"  value="${priceListInstance?.beginDate}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: priceListInstance, field: 'codeOfProduct', 'error')} required">
	<label for="codeOfProduct">
		<g:message code="priceList.codeOfProduct.label" default="Code Of Product" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="codeOfProduct" type="number" value="${priceListInstance.codeOfProduct}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: priceListInstance, field: 'endDate', 'error')} required">
	<label for="endDate">
		<g:message code="priceList.endDate.label" default="End Date" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="endDate" precision="day"  value="${priceListInstance?.endDate}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: priceListInstance, field: 'price', 'error')} required">
	<label for="price">
		<g:message code="priceList.price.label" default="Price" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="price" type="number" value="${priceListInstance.price}" required=""/>

</div>

grails-app/views/priceList/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'priceList.label', default: 'PriceList')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-priceList" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-priceList" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${priceListInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${priceListInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:priceListInstance, action:'changeDates']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>

		</div>
	</body>
</html>

grails-app/views/priceList/edit.gsp
<%@ page import="testtask.PriceList" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'priceList.label', default: 'PriceList')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-priceList" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-priceList" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${priceListInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${priceListInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:priceListInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${priceListInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/priceList/index.gsp
<%@ page import="testtask.PriceList" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'priceList.label', default: 'Цены')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-priceList" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}">На главную</a></li>
				<li><g:link class="create" action="create">Создать товар с временными ограничениями</g:link></li>
			</ul>
		</div>
		<div id="list-priceList" class="content scaffold-list" role="main">
			<h1>Список товаров</h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			${res}
			<table>
			<thead>
					<tr>
						<g:sortableColumn property="codeOfProduct" title="${message(code: 'priceList.codeOfProduct.label', default: 'Код товара')}" />
					
						<g:sortableColumn property="beginDate" title="${message(code: 'priceList.beginDate.label', default: 'Начало действия цены')}" />
					
						<g:sortableColumn property="endDate" title="${message(code: 'priceList.endDate.label', default: 'Конец действия цены')}" />
					
						<g:sortableColumn property="price" title="${message(code: 'priceList.price.label', default: 'Цена')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${priceListInstanceList}" status="i" var="priceListInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

						<td>${fieldValue(bean: priceListInstance, field: "codeOfProduct")}</td>

						<td><g:link action="show" id="${priceListInstance.id}">${fieldValue(bean: priceListInstance, field: "beginDate")}</g:link></td>
					
						<td><g:formatDate date="${priceListInstance.endDate}" /></td>
					
						<td>${fieldValue(bean: priceListInstance, field: "price")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${priceListInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/priceList/show.gsp
<%@ page import="testtask.PriceList" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'priceList.label', default: 'PriceList')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-priceList" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-priceList" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list priceList">
			
				<g:if test="${priceListInstance?.beginDate}">
				<li class="fieldcontain">
					<span id="beginDate-label" class="property-label"><g:message code="priceList.beginDate.label" default="Begin Date" /></span>
					
						<span class="property-value" aria-labelledby="beginDate-label"><g:formatDate date="${priceListInstance?.beginDate}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceListInstance?.codeOfProduct}">
				<li class="fieldcontain">
					<span id="codeOfProduct-label" class="property-label"><g:message code="priceList.codeOfProduct.label" default="Code Of Product" /></span>
					
						<span class="property-value" aria-labelledby="codeOfProduct-label"><g:fieldValue bean="${priceListInstance}" field="codeOfProduct"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceListInstance?.endDate}">
				<li class="fieldcontain">
					<span id="endDate-label" class="property-label"><g:message code="priceList.endDate.label" default="End Date" /></span>
					
						<span class="property-value" aria-labelledby="endDate-label"><g:formatDate date="${priceListInstance?.endDate}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${priceListInstance?.price}">
				<li class="fieldcontain">
					<span id="price-label" class="property-label"><g:message code="priceList.price.label" default="Price" /></span>
					
						<span class="property-value" aria-labelledby="price-label"><g:fieldValue bean="${priceListInstance}" field="price"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:priceListInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">

					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>